apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: my-test-secret
  namespace: kube-system
spec:
  organizationId: "8b6e7054-a773-4eac-9d20-b2f500f8c99d"
  secretName: my-test-secret
  map: # This is now an array
    - bwSecretId: ed927d58-4a81-4776-be57-b30d01381228
      secretKeyName: test-secret
  authToken:
    secretName: bw-auth-token
    secretKey: token