apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  # Descriptive name for the BitwardenSecret resource itself
  name: synology-iscsi-bws-secret
spec:
  organizationId: "8b6e7054-a773-4eac-9d20-b2f500f8c99d"
  # This is the name of the Kubernetes secret that will be created and used by your service account
  secretName: "synology-iscsi-credentials"
  authToken:
    # This still points to the Bitwarden authentication token
    secretName: "bw-auth-token"
  map:
    # Map your Bitwarden secret's UUID to the desired key in the Kubernetes secret
    - bwSecretId: "086bead1-8a3d-4f38-ac70-b30c00f0e4ed"
      secretKeyName: "username"
    - bwSecretId: "489c6ee3-bf06-4d41-af12-b30c00dd876d"
      secretKeyName: "password"