apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  # This resource tells the Bitwarden Operator what to fetch from the vault.
  name: synology-iscsi-bws-secret
spec:
  organizationId: "8b6e7054-a773-4eac-9d20-b2f500f8c99d"
  # This will be the name of the final Kubernetes secret created in the 'storage' namespace.
  secretName: "bw-auth-token"
  authToken:
    # This points to the Kubernetes secret bootstrapped by manage-cluster.sh.
    # It must be in the same namespace as this BitwardenSecret resource.
    secretName: "bw-auth-token"
  # The 'map' defines which secrets from Bitwarden to pull and what to name their keys
  # in the final Kubernetes secret.
  map:
    # The username for the iSCSI service account.
    - bwSecretId: "086bead1-8a3d-4f38-ac70-b30c00f0e4ed"
      secretKeyName: "ISCSI_SERVICE_ACCOUNT"
    # The password for the iSCSI service account.
    - bwSecretId: "489c6ee3-bf06-4d41-af12-b30c00dd876d"
      secretKeyName: "ISCSI_SERVICE_ACCOUNT_PASSWORD"