# Create individual BitwardenSecret resources to avoid pulling all organization secrets
# This approach ensures only the specific secrets we want are retrieved
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: synology-iscsi-username-secret
  namespace: synology-csi
spec:
  organizationId: "8b6e7054-a773-4eac-9d20-b2f500f8c99d"
  secretName: "synology-iscsi-username"
  authToken:
    secretName: "bw-auth-token"
    secretKey: "token"
  map:
    - bwSecretId: "086bead1-8a3d-4f38-ac70-b30c00f0e4ed"
      secretKeyName: "ISCSI_SERVICE_ACCOUNT"
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: synology-iscsi-password-secret
  namespace: synology-csi
spec:
  organizationId: "8b6e7054-a773-4eac-9d20-b2f500f8c99d"
  secretName: "synology-iscsi-password"
  authToken:
    secretName: "bw-auth-token"
    secretKey: "token"
  map:
    - bwSecretId: "489c6ee3-bf06-4d41-af12-b30c00dd876d"
      secretKeyName: "ISCSI_SERVICE_ACCOUNT_PASSWORD"
