apiVersion: v1
kind: Secret
metadata:
  name: client-info-secret
  namespace: synology-csi
stringData:
  client-info.yml: |
    clients:
      - host: "NAS-Server.int.intergrem.com" # Replace with your Synology NAS IP
        username: "$(ISCSI_SERVICE_ACCOUNT)"
        password: "$(ISCSI_SERVICE_ACCOUNT_PASSWORD)"
        # Add other clients if needed
