# apps/storage/synology-iscsi-credentials/github-credentials.yaml
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bws-ghcr-secret
  namespace: synology-csi
spec:
  organizationId: "8b6e7054-a773-4eac-9d20-b2f500f8c99d"
  # Set the Kubernetes secret name to ghcr-secret
  secretName: "ghcr-secret"
  # Set the Kubernetes secret type
  secretType: kubernetes.io/dockerconfigjson
  authToken:
    secretName: "bw-auth-token"
    secretKey: "token"
  map:
    - bwSecretId: "SYNOLOGY_CSI_GITHUB_READ" # Ensure this is the correct ID from Bitwarden
      # Set the key within the Kubernetes secret
      secretKeyName: ".dockerconfigjson"