apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: synology-csi-github-read-secret
  namespace: synology-csi
spec:
  organizationId: "8b6e7054-a773-4eac-9d20-b2f500f8c99d"
  secretName: "SYNOLOGY_CSI_GITHUB_READ"
  authToken:
    secretName: "bw-auth-token"
    secretKey: "token"
  map:
    - bwSecretId: "SYNOLOGY_CSI_GITHUB_READ" # The user did not provide a UUID, so I'm using the name as a placeholder. This will likely need to be updated.
      secretKeyName: "DOCKER_CONFIG_JSON"
