apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: synology-csi
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: synology-csi-github-read-secret
  namespace: synology-csi
type: Opaque
data:
  DOCKER_CONFIG_JSON: ""
