# apps/storage/synology-csi-manual/credentials.yaml

# This secret holds the configuration for the CSI driver to connect to the NAS.
apiVersion: v1
kind: Secret
metadata:
  name: client-info-secret
  namespace: synology-csi
stringData:
  client-info.yml: |
    clients:
      - host: "NAS-Server.int.intergrem.com" # Replace with your Synology NAS IP
        username: "$(ISCSI_SERVICE_ACCOUNT)"
        password: "$(ISCSI_SERVICE_ACCOUNT_PASSWORD)"
---
# This BitwardenSecret resource creates the image pull secret (ghcr-secret).
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bws-ghcr-secret
  namespace: synology-csi
spec:
  organizationId: "8b6e7054-a773-4eac-9d20-b2f500f8c99d"
  # This is the name of the Kubernetes secret that will be created.
  secretName: "ghcr-secret"
  # This ensures the created secret has the correct type for image pulls.
  secretType: kubernetes.io/dockerconfigjson
  authToken:
    secretName: "bw-auth-token"
    secretKey: "token"
  map:
    # IMPORTANT: Ensure the Bitwarden secret with this ID contains the
    # full, valid dockerconfigjson content.
    - bwSecretId: "SYNOLOGY_CSI_GITHUB_READ" # NOTE: You may need to update this placeholder with the actual Bitwarden secret UUID.
      # This key name is required for a dockerconfigjson secret.
      secretKeyName: ".dockerconfigjson"