# apps/argocd/argocd/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  application.resourceTrackingMethod: annotation
  resource.customizations.ignoreResourceUpdates.v1_Service: |
    jqPathExpressions:
    - .spec.ports[].nodePort
  resource.customizations.health.apiextensions.k8s.io_CustomResourceDefinition: |
    hs = {}
    if obj.status ~= nil and obj.status.conditions ~= nil then
      for i, condition in ipairs(obj.status.conditions) do
        if condition.type == "Established" and condition.status == "True" then
          hs.status = "Healthy"
          hs.message = condition.message
          return hs
        end
        if condition.type == "NamesAccepted" and condition.status == "False" then
          hs.status = "Degraded"
          hs.message = condition.message
          return hs
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for CRD to be established"
    return hs