apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml

helmCharts:
  - name: synology-csi
    repo: https://zebernst.github.io/synology-csi-talos
    version: 0.10.1
    namespace: kube-system
    valuesFile: values.yaml
    includeCRDs: true
