# path: apps/kube-system/synology-csi/secret.yaml
# BitwardenSecret to create the synology-csi-client-info secret
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: synology-csi-credentials
  namespace: kube-system
  labels:
    app.kubernetes.io/name: synology-csi
    app.kubernetes.io/component: storage
spec:
  organizationId: "8b6e7054-a773-4eac-9d20-b2f500f8c99d"
  authToken:
    valueFrom:
      secretKeyRef:
        name: "bw-auth-token"
        key: "token"
  secretName: synology-csi-client-info
  # The 'map' now only retrieves the password from Bitwarden.
  map:
    - bwSecretId: "ISCSI_SERVICE_ACCOUNT_PASSWORD"
      secretKeyName: "iscsi_password"
  # The secret template now uses a static username.
  secretTemplate:
    type: Opaque
    stringData:
      client-info.yml: |
        clients:
        - host: "NAS-Storage.int.intergrem.com"
          port: 5000
          https: false
          username: "svc_iscsi"
          password: "{{ .iscsi_password }}"