apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "default-pool"
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  blocks:
  - start: "192.168.1.220"
    stop: "192.168.1.229"