apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ip-pool.yaml and l2-announcement-policy.yaml are now applied by manage-cluster.sh
# and should NOT be listed here.
resources:

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    version: v1.17.5
    releaseName: cilium
    namespace: kube-system
    valuesFile: values.yaml

patches:
  - path: patches/ingress-service-selector.yaml