cilium:
  # This setting was already correct
  kubeProxyReplacement: true

  # Enable L2 announcements feature
  l2announcements:
    enabled: true

  externalIPs:
    enabled: true
  ipam:
    mode: kubernetes
  securityContext:
    capabilities:
      ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETUID
        - SETGID
      cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
  cgroup:
    hostRoot: /sys/fs/cgroup
    autoMount:
      enabled: false
  ingressController:
    enabled: true
  k8sServiceHost: localhost
  k8sServicePort: 7445
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
      service:
        annotations:
          omni-kube-service-exposer.sidero.dev/port: "50080"
          omni-kube-service-exposer.sidero.dev/label: Hubble
          omni-kube-service-exposer.sidero.dev/prefix: Hubble
